#!/usr/bin/env ruby

$refname = ARGV[0]
$oldrev  = ARGV[1]
$newrev  = ARGV[2]
$user    = ENV['USER']

$regex = /\[ref: (\d+)\]/

puts "Enforcing Policies... \n(#{$refname}) (#{$oldrev}) (#{$newrev})"

# enforced custom commit message format
def check_message_format
  missed_refs = `git rev-list #{$oldrev}..#{$newrev}`.split("\n")
  missed_refs.each do |ref|
    message = `git cat-file commit #{ref} | sed '1,/^$/d'`
    if !$regex.match(message)
      puts "[POLICY] Your message is not formatted correctly"
      exit 1
    end
  end
end

# enforces fast-forward only pushes 
def check_fast_forward
  missed_refs = `git rev-list #{$newrev}..#{$oldrev}`
  missed_ref_count = missed_refs.split("\n").size
  if missed_ref_count > 0
    puts "[POLICY] Cannot push a non fast-forward reference"
    exit 1
  end
end

def get_acl_access_data
  # read in ACL data
  acl_file = File.read('acl').split("\n").reject { |line| line == '' || line[0] == '#' }
  access = {}
  acl_file.each do |line|
    avail, users, path = line.split('|')
    next unless avail == 'avail'
    users.split(',').each do |user|
      access[user] ||= []
      access[user] << path
    end
  end
  access
end

check_message_format

check_fast_forward

